spring:
  application:
    name: naroom-api
  config:
    import: optional:file:.env.local[.properties]
  profiles:
    default: local

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    version: openapi_3_1