package com.naroom.api.global.error.code;

public enum ClientAction {
	NONE,
	RETRY,
	CHECK_REQUEST,
	CHECK_DEVICE,
	LOGIN_REQUIRED,
	REFRESH_REQUIRED,
	CLEAR_SESSION_AND_LOGIN,
	COMPLETE_ONBOARDING,
	CONFIRM_ACCOUNT_RECOVERY,
	RELOAD_RESOURCE,
	CONTACT_SUPPORT
}
