-- Naroom Beta 1
-- Content (4), Record (4), Check-in (2)
-- PostgreSQL / Flyway

-- ---------------------------------------------------------------------------
-- Enum types
-- ---------------------------------------------------------------------------

CREATE TYPE quote_status AS ENUM (
    'DRAFT',
    'PUBLISHED',
    'ARCHIVED'
);

CREATE TYPE tag_category AS ENUM (
    'EMOTION',
    'SITUATION',
    'NEED',
    'VALUE',
    'ACTION',
    'RECOVERY',
    'CUSTOM'
);

CREATE TYPE tag_scope AS ENUM (
    'SYSTEM',
    'PRIVATE'
);

CREATE TYPE entry_type AS ENUM (
    'FREE',
    'CHECK_IN',
    'GRATITUDE',
    'EMOTION',
    'PROMPT',
    'QUOTE_REFLECTION',
    'EXPERIMENT_MISSION',
    'EXPERIMENT_REVIEW',
    'WEEKLY_REFLECTION',
    'SELF_SUMMARY'
);

CREATE TYPE entry_status AS ENUM (
    'DRAFT',
    'PUBLISHED'
);

CREATE TYPE entry_tag_source AS ENUM (
    'USER',
    'AI',
    'CHECK_IN',
    'REFLECTION',
    'EXPERIMENT'
);

CREATE TYPE entry_tag_status AS ENUM (
    'SUGGESTED',
    'ACCEPTED',
    'REJECTED',
    'SYSTEM'
);

-- ---------------------------------------------------------------------------
-- Content
-- ---------------------------------------------------------------------------

CREATE TABLE quote_topics (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(50)  NOT NULL,
    name            VARCHAR(100) NOT NULL,
    description     VARCHAR(500),
    display_order   INTEGER      NOT NULL DEFAULT 0,
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_quote_topics_code UNIQUE (code),
    CONSTRAINT ck_quote_topics_code_not_blank CHECK (BTRIM(code) <> ''),
    CONSTRAINT ck_quote_topics_name_not_blank CHECK (BTRIM(name) <> ''),
    CONSTRAINT ck_quote_topics_display_order CHECK (display_order >= 0)
);

CREATE TABLE quotes (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content             TEXT         NOT NULL,
    author_name         VARCHAR(200),
    source_title        VARCHAR(300),
    source_url          TEXT,
    status              quote_status NOT NULL DEFAULT 'DRAFT',
    publish_start_date  DATE,
    publish_end_date    DATE,
    display_order       INTEGER      NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_quotes_content_not_blank CHECK (BTRIM(content) <> ''),
    CONSTRAINT ck_quotes_author_name_not_blank
        CHECK (author_name IS NULL OR BTRIM(author_name) <> ''),
    CONSTRAINT ck_quotes_source_title_not_blank
        CHECK (source_title IS NULL OR BTRIM(source_title) <> ''),
    CONSTRAINT ck_quotes_publish_period
        CHECK (
            publish_start_date IS NULL
            OR publish_end_date IS NULL
            OR publish_start_date <= publish_end_date
        ),
    CONSTRAINT ck_quotes_display_order CHECK (display_order >= 0)
);

CREATE TABLE quote_topic_links (
    quote_id       BIGINT      NOT NULL,
    quote_topic_id BIGINT      NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_quote_topic_links PRIMARY KEY (quote_id, quote_topic_id),
    CONSTRAINT fk_quote_topic_links_quote
        FOREIGN KEY (quote_id) REFERENCES quotes (id) ON DELETE CASCADE,
    CONSTRAINT fk_quote_topic_links_topic
        FOREIGN KEY (quote_topic_id) REFERENCES quote_topics (id) ON DELETE CASCADE
);

CREATE TABLE member_saved_quotes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id  UUID        NOT NULL,
    quote_id   BIGINT      NOT NULL,
    saved_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_member_saved_quotes_member_quote UNIQUE (member_id, quote_id),
    CONSTRAINT fk_member_saved_quotes_member
        FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE CASCADE,
    CONSTRAINT fk_member_saved_quotes_quote
        FOREIGN KEY (quote_id) REFERENCES quotes (id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------------
-- Record
-- ---------------------------------------------------------------------------

CREATE TABLE tags (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_member_id     UUID,
    category            tag_category NOT NULL,
    scope               tag_scope    NOT NULL,
    name                 VARCHAR(100) NOT NULL,
    normalized_name      VARCHAR(100) NOT NULL,
    description          VARCHAR(500),
    display_order        INTEGER      NOT NULL DEFAULT 0,
    is_active            BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_tags_owner_member
        FOREIGN KEY (owner_member_id) REFERENCES members (id) ON DELETE CASCADE,
    CONSTRAINT ck_tags_name_not_blank CHECK (BTRIM(name) <> ''),
    CONSTRAINT ck_tags_normalized_name_not_blank CHECK (BTRIM(normalized_name) <> ''),
    CONSTRAINT ck_tags_display_order CHECK (display_order >= 0),
    CONSTRAINT ck_tags_scope_owner CHECK (
        (scope = 'SYSTEM' AND owner_member_id IS NULL)
        OR (scope = 'PRIVATE' AND owner_member_id IS NOT NULL)
    )
);

CREATE TABLE entries (
    id                  UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    member_id           UUID         NOT NULL,
    parent_entry_id     UUID,
    quote_id            BIGINT,
    type                entry_type   NOT NULL,
    status              entry_status NOT NULL DEFAULT 'PUBLISHED',
    title               VARCHAR(200),
    content             TEXT         NOT NULL,
    entry_date          DATE         NOT NULL,
    occurred_at         TIMESTAMPTZ,
    allow_ai_analysis   BOOLEAN      NOT NULL DEFAULT TRUE,
    published_at        TIMESTAMPTZ,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version             BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT fk_entries_member
        FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE CASCADE,
    CONSTRAINT fk_entries_parent
        FOREIGN KEY (parent_entry_id) REFERENCES entries (id) ON DELETE SET NULL,
    CONSTRAINT fk_entries_quote
        FOREIGN KEY (quote_id) REFERENCES quotes (id) ON DELETE SET NULL,
    CONSTRAINT ck_entries_content_not_blank CHECK (BTRIM(content) <> ''),
    CONSTRAINT ck_entries_title_not_blank
        CHECK (title IS NULL OR BTRIM(title) <> ''),
    CONSTRAINT ck_entries_parent_not_self
        CHECK (parent_entry_id IS NULL OR parent_entry_id <> id),
    CONSTRAINT ck_entries_version CHECK (version >= 0),
    CONSTRAINT ck_entries_publish_state CHECK (
        (status = 'DRAFT' AND published_at IS NULL)
        OR (status = 'PUBLISHED' AND published_at IS NOT NULL)
    ),
    CONSTRAINT ck_entries_quote_type CHECK (
        quote_id IS NULL OR type = 'QUOTE_REFLECTION'
    )
);

CREATE TABLE entry_tags (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id    UUID             NOT NULL,
    tag_id      BIGINT           NOT NULL,
    source      entry_tag_source NOT NULL,
    status      entry_tag_status NOT NULL,
    confidence  NUMERIC(5, 4),
    created_at  TIMESTAMPTZ      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ      NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_entry_tags_entry_tag UNIQUE (entry_id, tag_id),
    CONSTRAINT fk_entry_tags_entry
        FOREIGN KEY (entry_id) REFERENCES entries (id) ON DELETE CASCADE,
    CONSTRAINT fk_entry_tags_tag
        FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE RESTRICT,
    CONSTRAINT ck_entry_tags_confidence
        CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
    CONSTRAINT ck_entry_tags_ai_confidence
        CHECK (source = 'AI' OR confidence IS NULL)
);

CREATE TABLE entry_self_reflections (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    entry_id    UUID        NOT NULL,
    member_id   UUID        NOT NULL,
    content     TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version     BIGINT      NOT NULL DEFAULT 0,

    CONSTRAINT uk_entry_self_reflections_entry UNIQUE (entry_id),
    CONSTRAINT fk_entry_self_reflections_entry
        FOREIGN KEY (entry_id) REFERENCES entries (id) ON DELETE CASCADE,
    CONSTRAINT fk_entry_self_reflections_member
        FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE CASCADE,
    CONSTRAINT ck_entry_self_reflections_content_not_blank CHECK (BTRIM(content) <> ''),
    CONSTRAINT ck_entry_self_reflections_version CHECK (version >= 0)
);

-- ---------------------------------------------------------------------------
-- Check-in
-- ---------------------------------------------------------------------------

CREATE TABLE check_ins (
    id                    UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    member_id             UUID        NOT NULL,
    entry_id              UUID        NOT NULL,
    check_in_date         DATE        NOT NULL,
    emotion_intensity     SMALLINT,
    energy_level          SMALLINT,
    memorable_event       TEXT,
    gratitude_note        TEXT,
    current_need          TEXT,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version               BIGINT      NOT NULL DEFAULT 0,

    CONSTRAINT uk_check_ins_member_date UNIQUE (member_id, check_in_date),
    CONSTRAINT uk_check_ins_entry UNIQUE (entry_id),
    CONSTRAINT fk_check_ins_member
        FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE CASCADE,
    CONSTRAINT fk_check_ins_entry
        FOREIGN KEY (entry_id) REFERENCES entries (id) ON DELETE CASCADE,
    CONSTRAINT ck_check_ins_emotion_intensity
        CHECK (emotion_intensity IS NULL OR emotion_intensity BETWEEN 1 AND 5),
    CONSTRAINT ck_check_ins_energy_level
        CHECK (energy_level IS NULL OR energy_level BETWEEN 1 AND 5),
    CONSTRAINT ck_check_ins_memorable_event_not_blank
        CHECK (memorable_event IS NULL OR BTRIM(memorable_event) <> ''),
    CONSTRAINT ck_check_ins_gratitude_note_not_blank
        CHECK (gratitude_note IS NULL OR BTRIM(gratitude_note) <> ''),
    CONSTRAINT ck_check_ins_current_need_not_blank
        CHECK (current_need IS NULL OR BTRIM(current_need) <> ''),
    CONSTRAINT ck_check_ins_has_content CHECK (
        emotion_intensity IS NOT NULL
        OR energy_level IS NOT NULL
        OR memorable_event IS NOT NULL
        OR gratitude_note IS NOT NULL
        OR current_need IS NOT NULL
    ),
    CONSTRAINT ck_check_ins_version CHECK (version >= 0)
);

CREATE TABLE check_in_emotions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    check_in_id  UUID        NOT NULL,
    tag_id       BIGINT      NOT NULL,
    display_order SMALLINT   NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_check_in_emotions_check_in_tag UNIQUE (check_in_id, tag_id),
    CONSTRAINT fk_check_in_emotions_check_in
        FOREIGN KEY (check_in_id) REFERENCES check_ins (id) ON DELETE CASCADE,
    CONSTRAINT fk_check_in_emotions_tag
        FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE RESTRICT,
    CONSTRAINT ck_check_in_emotions_display_order CHECK (display_order >= 0)
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

CREATE INDEX idx_quotes_status_publish_dates
    ON quotes (status, publish_start_date, publish_end_date);

CREATE INDEX idx_quote_topic_links_topic
    ON quote_topic_links (quote_topic_id, quote_id);

CREATE INDEX idx_member_saved_quotes_member_saved_at
    ON member_saved_quotes (member_id, saved_at DESC);

CREATE UNIQUE INDEX uk_tags_system_normalized_name
    ON tags (category, normalized_name)
    WHERE scope = 'SYSTEM';

CREATE UNIQUE INDEX uk_tags_private_owner_normalized_name
    ON tags (owner_member_id, category, normalized_name)
    WHERE scope = 'PRIVATE';

CREATE INDEX idx_tags_system_category_order
    ON tags (category, display_order, id)
    WHERE scope = 'SYSTEM' AND is_active = TRUE;

CREATE INDEX idx_tags_private_owner_category
    ON tags (owner_member_id, category, created_at DESC)
    WHERE scope = 'PRIVATE';

CREATE INDEX idx_entries_member_date
    ON entries (member_id, entry_date DESC, created_at DESC);

CREATE INDEX idx_entries_member_type_date
    ON entries (member_id, type, entry_date DESC);

CREATE INDEX idx_entries_parent
    ON entries (parent_entry_id)
    WHERE parent_entry_id IS NOT NULL;

CREATE INDEX idx_entries_quote
    ON entries (quote_id)
    WHERE quote_id IS NOT NULL;

CREATE INDEX idx_entry_tags_tag_entry
    ON entry_tags (tag_id, entry_id);

CREATE INDEX idx_entry_tags_entry_status
    ON entry_tags (entry_id, status);

CREATE INDEX idx_entry_self_reflections_member_created_at
    ON entry_self_reflections (member_id, created_at DESC);

CREATE INDEX idx_check_ins_member_date
    ON check_ins (member_id, check_in_date DESC);

CREATE INDEX idx_check_in_emotions_tag
    ON check_in_emotions (tag_id, check_in_id);

-- PostgreSQL CHECK constraints cannot verify values in referenced rows.
-- The application must additionally enforce:
-- 1. entries.parent_entry_id belongs to the same member.
-- 2. entry_self_reflections.member_id equals the referenced entry's member_id.
-- 3. check_ins.member_id equals the referenced entry's member_id.
-- 4. check_ins.entry_id references an entry whose type is CHECK_IN.
-- 5. check_in_emotions.tag_id references an EMOTION tag visible to that member.
-- 6. PRIVATE tags can only be linked to records owned by the same member.
